server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/sadseven/configure-repo
          searchPaths: repo
          username: 
          password:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

